### ISSUE TITLE
Add support for a filtering system

### ISSUE THREAD

**Issue by mikerockett** [LulububuSoftwareGmbH/boltredirector#4]
Whilst building a site on Bolt, I found the need to redirect `/share-on/<social_network>/<slug>` to the respective social network's sharing URL. As such, I  thought that URL encoding should be done before the actual redirect.

So, I'm working on a quick feature-add that let's you do this:

``` yml
share_on_facebook:
    from: 'share-on/facebook/{path}'
    to: 'https://www.facebook.com/sharer/sharer.php?u=[{@url_root}/{path}|e]'
```

Notice the square brackets with the `|e`? That's the new filtering 'system'. It'll perform all the necessary replacements, and then encode the result.

Other filters will be:

`be`: Base 64 Encode
`bd`: Base 64 Decode

If you can think of any others that should be added, please do add them in the comments.

(PS: `@url_root` is a new global variable, which imports the current host URL.)
